### ISSUE TITLE
What is the difference between the SVTRv2 mentioned in this repository's and the SVTRv2 in the PaddleOCR?

### ISSUE THREAD

**Issue by Xelawk** [Topdu/OpenOCR#62]
Could you please explain the difference between the SVTRv2 introduced in the PaddleOCR documentation (https://paddlepaddle.github.io/PaddleOCR/latest/algorithm/text_recognition/algorithm_rec_svtrv2.html#33) and the SVTRv2 mentioned in this repository's OpenOCR project?

**Comment by Topdu** [comment]
First of all, SVTRv2 is an article on SOTA scene text recognition methods for academic research. Based on SVTRv2, we developed the accurate and efficient OCR system OpenOCR, which can be considered as a practical version of SVTRv2, trained on datasets from a variety of scenarios.SVTRv2 in PaddleOCR is a PaddlePaddle implementation of OpenOCR, with no difference in model structure.

**Comment by leduy-it** [comment]
@Topdu 

I noticed that while the encoder in OpenOCR and PaddleOCR is similar, their decoders differ significantly. I really appreciate the ratio group dataset loader, but I've encountered considerable challenges during evaluation, particularly with deep recursion issues in the batch processing.

In PaddleOCR, the implementation uses a CTC head with a 1x3 kernel instead of the 3x3 kernel found in the SVTR encoder neck. This is further combined with a GTC head, referred to as the NRTR head. On the other hand, OpenOCR employs RCTC and GTC heads, with the GTC head implemented as a Sub-String Matching GTC head.

These differences make it challenging to decide on the most appropriate head for my use case. Currently, I’m facing issues with the SVTR-CTC-GTC-head configuration in PaddleOCR, which often produces almost duplicate outputs for hieroglyph recognition.

I've attached an example below for reference. Any guidance on resolving this or advice on the optimal head configuration would be greatly appreciated.
---
Issue Description:
I am encountering two main problems with text recognition:

    Duplicate Characters in Short Text: Short text inputs frequently produce duplicate characters in the output.
    Missing Characters in Long Text: Long text inputs often result in missing characters in the recognized output.

I’ve ensured that the input images are resized with padding and without distortion, so the issue does not seem to stem from preprocessing.
----
![image](https://github.com/user-attachments/assets/131e81ee-77a7-497d-a5f9-bf533d4d56a9)
![image](https://github.com/user-attachments/assets/64248659-4212-4c9c-996e-252ec48a41b6)

**Comment by Topdu** [comment]
Handwritten text recognition is inherently more challenging than printed text recognition. If you aim for higher recognition accuracy and are less concerned about inference speed, you can directly use the NRTRHead model in PaddleOCR for handwriting recognition, instead of using the CTCHead. It requires modification of PaddleOCR's configuration files and codes.

Furthermore, in the OpenOCR system, the model configuration files for mobile and server recognition model are `RepSVTR_ch.yml` and `SVTRv2_ch.yml`, respectively. These configurations do not utilize RCTC and SGM. RCTC and SGM are strategies designed to address the limitations of CTC models in recognizing irregular text and modeling semantic context. The configuration files that include RCTC and SGM are `svtrv2_smtr_gtc_rctc*.yml`.

When using `svtrv2_smtr_gtc_rctc*.yml`, its performance might not be as good as `SVTRv2_ch.yml`. This is because, in order to provide a fair comparison with the STR methods from academic papers, the `svtrv2_smtr_gtc_rctc*.yml` configuration is trained on commonly used benchmark datasets. In contrast, `SVTRv2_ch.yml` has been trained on a more diverse and broader dataset, making it more practical for real-world applications.

**Comment by Laki-Cat** [comment]
> Handwritten text recognition is inherently more challenging than printed text recognition. If you aim for higher recognition accuracy and are less concerned about inference speed, you can directly use the NRTRHead model in PaddleOCR for handwriting recognition, instead of using the CTCHead. It requires modification of PaddleOCR's configuration files and codes.
> 
> Furthermore, in the OpenOCR system, the model configuration files for mobile and server recognition model are `RepSVTR_ch.yml` and `SVTRv2_ch.yml`, respectively. These configurations do not utilize RCTC and SGM. RCTC and SGM are strategies designed to address the limitations of CTC models in recognizing irregular text and modeling semantic context. The configuration files that include RCTC and SGM are `svtrv2_smtr_gtc_rctc*.yml`.
> 
> When using `svtrv2_smtr_gtc_rctc*.yml`, its performance might not be as good as `SVTRv2_ch.yml`. This is because, in order to provide a fair comparison with the STR methods from academic papers, the `svtrv2_smtr_gtc_rctc*.yml` configuration is trained on commonly used benchmark datasets. In contrast, `SVTRv2_ch.yml` has been trained on a more diverse and broader dataset, making it more practical for real-world applications.

But I see that in mmocr, svtr works better than nrtr

**Comment by Laki-Cat** [comment]
> 手写文本识别本质上比印刷文本识别更具挑战性。如果您追求更高的识别准确率，而不太在意推理速度，您可以直接使用 PaddleOCR 中的 NRTRHead 模型进行手写识别，而不必使用 CTCHead。这需要修改 PaddleOCR 的配置文件和代码。
> 
> 此外，在OpenOCR系统中，移动端和服务器识别模型的模型配置文件分别为`RepSVTR_ch.yml`和`SVTRv2_ch.yml`。这些配置没有使用RCTC和SGM。RCTC和SGM是为了解决CTC模型在识别不规则文本和建模语义上下文方面的局限性而设计的策略。包含RCTC和SGM的配置文件为`svtrv2_smtr_gtc_rctc*.yml`。
> 
> 使用 时`svtrv2_smtr_gtc_rctc*.yml`，其性能可能不如`SVTRv2_ch.yml`。这是因为，为了与学术论文中的 STR 方法进行公平比较，该`svtrv2_smtr_gtc_rctc*.yml`配置是在常用的基准数据集上进行训练的。相比之下，`SVTRv2_ch.yml`是在更多样化和更广泛的数据集上进行训练的，使其更适合实际应用。

But I noticed that in MMOCR, SVTR scores higher than NRTR. Does this mean that NRTR performs better in handwriting scenarios, while SVTR performs better in general scenarios?

**Comment by Laki-Cat** [comment]
> Handwritten text recognition is inherently more challenging than printed text recognition. If you aim for higher recognition accuracy and are less concerned about inference speed, you can directly use the NRTRHead model in PaddleOCR for handwriting recognition, instead of using the CTCHead. It requires modification of PaddleOCR's configuration files and codes.
> 
> Furthermore, in the OpenOCR system, the model configuration files for mobile and server recognition model are `RepSVTR_ch.yml` and `SVTRv2_ch.yml`, respectively. These configurations do not utilize RCTC and SGM. RCTC and SGM are strategies designed to address the limitations of CTC models in recognizing irregular text and modeling semantic context. The configuration files that include RCTC and SGM are `svtrv2_smtr_gtc_rctc*.yml`.
> 
> When using `svtrv2_smtr_gtc_rctc*.yml`, its performance might not be as good as `SVTRv2_ch.yml`. This is because, in order to provide a fair comparison with the STR methods from academic papers, the `svtrv2_smtr_gtc_rctc*.yml` configuration is trained on commonly used benchmark datasets. In contrast, `SVTRv2_ch.yml` has been trained on a more diverse and broader dataset, making it more practical for real-world applications.

But I noticed that in MMOCR ( https://github.com/open-mmlab/mmocr/tree/main ) , SVTR scores higher than NRTR. Does this mean that NRTR performs better in handwriting scenarios, while SVTR performs better in general scenarios?

**Comment by leduy-it** [comment]
> Handwritten text recognition is inherently more challenging than printed text recognition. If you aim for higher recognition accuracy and are less concerned about inference speed, you can directly use the NRTRHead model in PaddleOCR for handwriting recognition, instead of using the CTCHead. It requires modification of PaddleOCR's configuration files and codes.
> 
> Furthermore, in the OpenOCR system, the model configuration files for mobile and server recognition model are `RepSVTR_ch.yml` and `SVTRv2_ch.yml`, respectively. These configurations do not utilize RCTC and SGM. RCTC and SGM are strategies designed to address the limitations of CTC models in recognizing irregular text and modeling semantic context. The configuration files that include RCTC and SGM are `svtrv2_smtr_gtc_rctc*.yml`.
> 
> When using `svtrv2_smtr_gtc_rctc*.yml`, its performance might not be as good as `SVTRv2_ch.yml`. This is because, in order to provide a fair comparison with the STR methods from academic papers, the `svtrv2_smtr_gtc_rctc*.yml` configuration is trained on commonly used benchmark datasets. In contrast, `SVTRv2_ch.yml` has been trained on a more diverse and broader dataset, making it more practical for real-world applications.

Hi, thank you for your explanation and for your great work on PaddleOCR!

I have a follow-up question regarding the last point you mentioned. You noted that svtrv2_smtr_gtc_rctc*.yml might not perform as well as SVTRv2_ch.yml due to differences in training datasets. I understand this is to ensure a fair comparison with other STR methods on benchmark datasets.

However, let's say we train both models (SVTRv2_ch.yml and svtrv2_smtr_gtc_rctc*.yml) on the same real-world dataset, for example, documents in Chinese that often contain long lines of text, with width-to-height ratios as high as 20. In this case, wouldn’t the use of RCTC and SGM—which capture semantic context—lead to better recognition accuracy than standard SVTRv2 with CTC loss?

From what I understand, CTC loss may not be ideal for very long and complex line texts, since it lacks the ability to model semantic context, which seems essential in such scenarios.

That brings me to my main question: Since OpenOCR is already aimed at real-world scenarios, why does it still use the traditional CTC-based SVTRv2 as the default? Wouldn’t it make more sense to switch to RCTC + SGM-based models if they’re semantically stronger and better suited for real documents?

Looking forward to your insights. Thanks again!

**Comment by leduy-it** [comment]
Hi @Topdu, could you take a look at this when you have a moment? 🙏

It’s a great point about the potential advantages of RCTC + SGM for long, complex lines in real-world documents, especially with high width-to-height ratios. Would love to hear your thoughts on whether OpenOCR might consider shifting default configurations in favor of semantically richer approaches for such cases.

Thanks again!

**Comment by Topdu** [comment]
We have received your insightful suggestions, and we are very grateful. It is important to emphasize that we use CTC as the decoder because it allows for faster text recognition. If speed is not a requirement in the scenario you mentioned, using **SVTRv2 + SMTR** typically yields better results. In the future, we will consider providing a practical version of SVTRv2 + SMTR, which will be trained on the same dataset as **SVTRv2_ch**.

**Comment by bely66** [comment]
Hi @Topdu 

<img width="290" alt="Image" src="https://github.com/user-attachments/assets/d1da42b2-5869-4df1-9b87-3cdd553c211a" />

<img width="220" alt="Image" src="https://github.com/user-attachments/assets/9ae20cb4-706b-40ed-a5cd-0d3f014269d2" />

Thanks for the amazing, after checking the config files before training, i found that the img size and max character are very small, meaning that the detection has to be word level which is very limiting for real world applications where recognition models will have a document with multiple lines, and detecting word by word introduces a lot of post processing challenges

How do you handle that in openOCR?
